"""
report.py

Generates the final output from the structured findings dict and the
LLM interpretation string. Produces two files: a JSON findings file
for machine consumption and a markdown report for human reading.

Both files are written to an output directory that is created if it
does not already exist. The output path is configurable.
"""

import json
import os
from pathlib import Path
from datetime import datetime


def write_report(
    findings: dict,
    interpretation: str,
    stl_path: str,
    output_dir: str = "output",
) -> dict:
    """
    Write the JSON findings file and markdown report to the output directory.

    Parameters
    ----------
    findings : dict
        Unified findings package from aggregate.run_all_checks().
    interpretation : str
        Natural language interpretation from interpret.interpret_findings().
    stl_path : str
        Path to the original STL file, used for labeling the report.
    output_dir : str
        Directory to write output files. Created if it does not exist.

    Returns
    -------
    dict
        Paths to the written files under keys 'json_path' and 'md_path'.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    stem = Path(stl_path).stem
    base_name = f"{stem}_{timestamp}"

    full_output = {
        "meta": {
            "stl_file": str(stl_path),
            "timestamp": timestamp,
            "model": "claude-sonnet-4-6",
        },
        "findings": findings,
        "interpretation": interpretation,
    }

    json_path = output_path / f"{base_name}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(full_output, f, indent=2)

    md_path = output_path / f"{base_name}.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(_build_markdown(findings, interpretation, stl_path, timestamp))

    return {
        "json_path": str(json_path),
        "md_path": str(md_path),
    }


def _build_markdown(
    findings: dict,
    interpretation: str,
    stl_path: str,
    timestamp: str,
) -> str:
    """
    Build the markdown report string from findings and interpretation.

    Parameters
    ----------
    findings : dict
        Unified findings package.
    interpretation : str
        LLM interpretation.
    stl_path : str
        Original STL file path.
    timestamp : str
        Formatted timestamp string.

    Returns
    -------
    str
        Complete markdown document as a string.
    """
    mesh = findings["mesh_summary"]
    overall = findings["overall_severity"].upper()
    checks = findings["checks"]

    severity_emoji = {
        "HIGH": "🔴",
        "MEDIUM": "🟡",
        "LOW": "🟢",
        "PASS": "✅",
        "INCONCLUSIVE": "⚪",
    }
    icon = severity_emoji.get(overall, "⚪")

    lines = [
        f"# CAD Auditor: DFM Report",
        f"",
        f"**File:** `{Path(stl_path).name}`  ",
        f"**Date:** {timestamp}  ",
        f"**Overall severity:** {icon} {overall}",
        f"",
        f"---",
        f"",
        f"## Mesh Summary",
        f"",
        f"| Property | Value |",
        f"|---|---|",
        f"| Faces | {mesh['face_count']:,} |",
        f"| Vertices | {mesh['vertex_count']:,} |",
        f"| Bounding box | {mesh['bounding_box_mm']['x']} x "
        f"{mesh['bounding_box_mm']['y']} x "
        f"{mesh['bounding_box_mm']['z']} mm |",
        f"| Watertight | {'Yes' if mesh['is_watertight'] else 'No'} |",
        f"| Surface area | {mesh['surface_area_mm2']:,} mm² |",
        f"",
        f"---",
        f"",
        f"## Check Results",
        f"",
    ]

    for key, check in checks.items():
        sev = check["severity"].upper()
        icon_check = severity_emoji.get(sev, "⚪")
        lines.append(f"### {icon_check} {check['category'].replace('_', ' ').title()}")
        lines.append(f"")
        lines.append(f"**Severity:** {sev}")
        lines.append(f"")
        lines.append(f"{check['description']}")
        lines.append(f"")
        if check.get("methodology_note"):
            lines.append(f"*{check['methodology_note']}*")
            lines.append(f"")

    lines += [
        f"---",
        f"",
        f"## DFM Assessment",
        f"",
        interpretation,
        f"",
        f"---",
        f"",
        f"*Generated by CAD Auditor. "
        f"Geometric analysis is deterministic. "
        f"Interpretation generated by Claude claude-sonnet-4-6.*",
    ]

    return "\n".join(lines)